#ifndef __MyFrame__
#define __MyFrame__

/**
@file
Subclass of IGuessFrame, which is generated by wxFormBuilder.
*/

#include "IGuessFrame.h"

#include "wx/wxprec.h"
#ifndef WX_PRECOMP    
#include "wx/wx.h"
#endif

#include <vector>

//// end generated include
namespace zks {
    namespace game {
        namespace guess {
            /** Implementing IGuessFrame */
            class MyFrame : public IGuessFrame
            {
            protected:
                void UpdateStatBMP();
                // Handlers for IGuessFrame events.
                void OnHead(wxCommandEvent& event);
                void OnPrev(wxCommandEvent& event);
                void OnNext(wxCommandEvent& event);
                void OnTail(wxCommandEvent& event);
                void OnGuessInput(wxCommandEvent& event);
                void OnGuessEnter(wxCommandEvent& event);
                void OnFileOpenFolder(wxCommandEvent& event);
                void OnFileExit(wxCommandEvent& event);
                void StartGuessName();
                void ProvidePuzzle();
                wxString GetNameFromFile(const wxString& fn);
                void GNHint();
                void OnHintChecker(wxCommandEvent& event);
            public:
                /** Constructor */
                MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size);
                //// end generated class members
            private:
                wxLog *m_log;
                wxString m_pic_dir;
                std::vector<wxImage> m_images;
                int m_gn_index;
                wxArrayString m_gn_names;
                bool m_hint;
            };
        }
    }
}


#endif // __MyFrame__
